[package]
name = "sweem_core"
edition = "2024"

[dependencies]
sweem_registry = { local = "../sweem_registry" }
openzeppelin_math = { git = "https://github.com/OpenZeppelin/contracts-sui.git", subdir = "math/core", rev = "6df7fd42f6560a65bc487a9d5858ee22f65400f7" }
openzeppelin_access = { git = "https://github.com/OpenZeppelin/contracts-sui.git", subdir = "contracts/access", rev = "6df7fd42f6560a65bc487a9d5858ee22f65400f7" }
